const logo = (name: string) => `/${encodeURIComponent(name)}.png`;

export const marqueeLogos = [
  { src: logo('123 Dentist'),                       name: '123 Dentist' },
  { src: logo('ABC Dental'),                         name: 'ABC Dental' },
  { src: logo('Al Safa'),                            name: 'Al Safa' },
  { src: logo('Al-Shamas'),                          name: 'Al-Shamas' },
  { src: logo('Amazon'),                             name: 'Amazon' },
  { src: logo('Amope'),                              name: 'Amope' },
  { src: logo('Art & Science'),                      name: 'Art & Science' },
  { src: logo('Auto-Star'),                          name: 'Auto-Star' },
  { src: logo('BeeMaid'),                            name: 'BeeMaid' },
  { src: logo("Bishop's University"),                name: "Bishop's University" },
  { src: logo('Brightside'),                         name: 'Brightside' },
  { src: logo('Canada Health Infoway'),              name: 'Canada Health Infoway' },
  { src: logo('CanadaHelps'),                        name: 'CanadaHelps' },
  { src: logo('CanPR'),                              name: 'CanPR' },
  { src: logo('Carlsberg'),                          name: 'Carlsberg' },
  { src: logo('Century 21'),                         name: 'Century 21' },
  { src: logo('City Contractors'),                   name: 'City Contractors' },
  { src: logo('City Electric Supply'),               name: 'City Electric Supply' },
  { src: logo('Clorox'),                             name: 'Clorox' },
  { src: logo('Convergent Dentistry'),               name: 'Convergent Dentistry' },
  { src: logo('Costi'),                              name: 'Costi' },
  { src: logo('Dasco'),                              name: 'Dasco' },
  { src: logo('DHL'),                                name: 'DHL' },
  { src: logo('Discount'),                           name: 'Discount' },
  { src: logo('Durex'),                              name: 'Durex' },
  { src: logo('Enfamil'),                            name: 'Enfamil' },
  { src: logo('FGF'),                                name: 'FGF' },
  { src: logo('Fido'),                               name: 'Fido' },
  { src: logo('Finish'),                             name: 'Finish' },
  { src: logo("Frank's RedHot"),                     name: "Frank's RedHot" },
  { src: logo("French's"),                           name: "French's" },
  { src: logo('Genesis'),                            name: 'Genesis' },
  { src: logo('Google'),                             name: 'Google' },
  { src: logo('Guinness'),                           name: 'Guinness' },
  { src: logo('Habib Canadian Bank'),                name: 'Habib Canadian Bank' },
  { src: logo('Halifax Regional Centre for Education'), name: 'Halifax Regional Centre for Education' },
  { src: logo('Hatch Group'),                        name: 'Hatch Group' },
  { src: logo('Heinz'),                              name: 'Heinz' },
  { src: logo('Herschel'),                           name: 'Herschel' },
  { src: logo('Hoegaarden'),                         name: 'Hoegaarden' },
  { src: logo('Hoka'),                               name: 'Hoka' },
  { src: logo('Huawei'),                             name: 'Huawei' },
  { src: logo('ICNA Canada'),                        name: 'ICNA Canada' },
  { src: logo('Intel'),                              name: 'Intel' },
  { src: logo('Iron Vegan'),                         name: 'Iron Vegan' },
  { src: logo('Islamic Relief'),                     name: 'Islamic Relief' },
  { src: logo('J&F Seafood'),                        name: 'J&F Seafood' },
  { src: logo('Jamieson'),                           name: 'Jamieson' },
  { src: logo('Janes'),                              name: 'Janes' },
  { src: logo('Jumbaloo'),                           name: 'Jumbaloo' },
  { src: logo('KFC'),                                name: 'KFC' },
  { src: logo('KFI'),                                name: 'KFI' },
  { src: logo('Kijiji'),                             name: 'Kijiji' },
  { src: logo('Kristin Ess'),                        name: 'Kristin Ess' },
  { src: logo('Kruger Products'),                    name: 'Kruger Products' },
  { src: logo('Lokma'),                              name: 'Lokma' },
  { src: logo('Lululemon'),                          name: 'Lululemon' },
  { src: logo('Lysol'),                              name: 'Lysol' },
  { src: logo('Made Good'),                          name: 'Made Good' },
  { src: logo('Make A Wish'),                        name: 'Make A Wish' },
  { src: logo('Manulife'),                           name: 'Manulife' },
  { src: logo('Marina Commodities'),                 name: 'Marina Commodities' },
  { src: logo('MBioTech'),                           name: 'MBioTech' },
  { src: logo('Mead Johnson Nutrition'),             name: 'Mead Johnson Nutrition' },
  { src: logo('Milk-Bone'),                          name: 'Milk-Bone' },
  { src: logo('MinMaxx'),                            name: 'MinMaxx' },
  { src: logo('Molson'),                             name: 'Molson' },
  { src: logo('Monarch Dentistry'),                  name: 'Monarch Dentistry' },
  { src: logo('Motrin'),                             name: 'Motrin' },
  { src: logo('Mr. Lube'),                           name: 'Mr. Lube' },
  { src: logo('MTR'),                                name: 'MTR' },
  { src: logo('Munk School'),                        name: 'Munk School' },
  { src: logo('Muslim Fest'),                        name: 'Muslim Fest' },
  { src: logo('MyRec Basketball'),                   name: 'MyRec Basketball' },
  { src: logo('National'),                           name: 'National' },
  { src: logo('Netflix'),                            name: 'Netflix' },
  { src: logo('Nike'),                               name: 'Nike' },
  { src: logo('Northern Bars'),                      name: 'Northern Bars' },
  { src: logo('One Dental'),                         name: 'One Dental' },
  { src: logo('Opal Hospitality'),                   name: 'Opal Hospitality' },
  { src: logo('Paramount Butcher Shop'),             name: 'Paramount Butcher Shop' },
  { src: logo('PetSmart'),                           name: 'PetSmart' },
  { src: logo('Plaza Premium'),                      name: 'Plaza Premium' },
  { src: logo('Proof Experiences'),                  name: 'Proof Experiences' },
  { src: logo('RBC'),                                name: 'RBC' },
  { src: logo("Reader's Digest"),                    name: "Reader's Digest" },
  { src: logo('Reckitt'),                            name: 'Reckitt' },
  { src: logo('Red Bull'),                           name: 'Red Bull' },
  { src: logo('Riverside Natural Foods Ltd'),        name: 'Riverside Natural Foods Ltd' },
  { src: logo('Rotman'),                             name: 'Rotman' },
  { src: logo('Royal LePage'),                       name: 'Royal LePage' },
  { src: logo('RSA'),                                name: 'RSA' },
  { src: logo('Rubicon'),                            name: 'Rubicon' },
  { src: logo('Samsung'),                            name: 'Samsung' },
  { src: logo('Sargent Farms'),                      name: 'Sargent Farms' },
  { src: logo('Scotiabank'),                         name: 'Scotiabank' },
  { src: logo('Shan'),                               name: 'Shan' },
  { src: logo('Shana'),                              name: 'Shana' },
  { src: logo('Shopify'),                            name: 'Shopify' },
  { src: logo('Skip'),                               name: 'Skip' },
  { src: logo('Smirnoff'),                           name: 'Smirnoff' },
  { src: logo("Smucker's"),                          name: "Smucker's" },
  { src: logo('Sofina'),                             name: 'Sofina' },
  { src: logo('Somersby'),                           name: 'Somersby' },
  { src: logo('Sony Music'),                         name: 'Sony Music' },
  { src: logo('Spotify'),                            name: 'Spotify' },
  { src: logo('Stonefire'),                          name: 'Stonefire' },
  { src: logo('Sun Life Financial'),                 name: 'Sun Life Financial' },
  { src: logo('Tata Tea'),                           name: 'Tata Tea' },
  { src: logo('Temp Transport'),                     name: 'Temp Transport' },
  { src: logo('The Brick Room'),                     name: 'The Brick Room' },
  { src: logo('The Co-operators'),                   name: 'The Co-operators' },
  { src: logo('Timberland'),                         name: 'Timberland' },
  { src: logo('TMU'),                                name: 'TMU' },
  { src: logo('Toyota'),                             name: 'Toyota' },
  { src: logo('Transcontinental'),                   name: 'Transcontinental' },
  { src: logo('Trevor Peter'),                       name: 'Trevor Peter' },
  { src: logo('Tylenol'),                            name: 'Tylenol' },
  { src: logo('Ugg'),                                name: 'Ugg' },
  { src: logo('Unify+'),                             name: 'Unify+' },
  { src: logo('Unilock'),                            name: 'Unilock' },
  { src: logo('Unilux HVAC'),                        name: 'Unilux HVAC' },
  { src: logo('UofT'),                               name: 'UofT' },
  { src: logo('Veet'),                               name: 'Veet' },
  { src: logo('Vive Social & PR'),                   name: 'Vive Social & PR' },
  { src: logo('Volvo'),                              name: 'Volvo' },
  { src: logo('Wasserman'),                          name: 'Wasserman' },
  { src: logo("World Parkinson's Program"),          name: "World Parkinson's Program" },
  { src: logo('York U'),                             name: 'York U' },
  { src: logo('Youtheory'),                          name: 'Youtheory' },
  { src: logo('YouTube'),                            name: 'YouTube' },
];

export const clientCards = [
  { src: logo('RBC'),            name: 'RBC',            industry: 'Banking & Finance',     detail: 'Branded merchandise and corporate gifting programs at scale.' },
  { src: logo('Scotiabank'),     name: 'Scotiabank',     industry: 'Banking & Finance',     detail: 'Custom kitting and promotional materials for branch campaigns.' },
  { src: logo('Manulife'),       name: 'Manulife',       industry: 'Insurance & Finance',   detail: 'Event collateral, signage, and branded apparel for national campaigns.' },
  { src: logo('Sun Life Financial'), name: 'Sun Life Financial', industry: 'Insurance',     detail: 'Co-packing and branded giveaways for client engagement programs.' },
  { src: logo('Shopify'),        name: 'Shopify',        industry: 'Technology',            detail: 'Custom merch and event kitting for product launches and summits.' },
  { src: logo('Google'),         name: 'Google',         industry: 'Technology',            detail: 'Premium branded swag and sampling activations for Canadian events.' },
  { src: logo('Amazon'),         name: 'Amazon',         industry: 'E-Commerce',            detail: 'Large-scale promotional kitting and workforce branded apparel.' },
  { src: logo('Netflix'),        name: 'Netflix',        industry: 'Entertainment',         detail: 'Experiential event signage and co-branded merchandise programs.' },
  { src: logo('Nike'),           name: 'Nike',           industry: 'Apparel & Sports',      detail: 'Team uniforms, awards programs, and retail display solutions.' },
  { src: logo('Lululemon'),      name: 'Lululemon',      industry: 'Apparel & Wellness',    detail: 'Custom apparel programs and in-store display kitting.' },
  { src: logo('Red Bull'),       name: 'Red Bull',       industry: 'Food & Beverage',       detail: 'Sampling events and branded activation materials across Canada.' },
  { src: logo('Molson'),         name: 'Molson',         industry: 'Food & Beverage',       detail: 'Promotional merchandise and retail point-of-sale displays.' },
  { src: logo('Toyota'),         name: 'Toyota',         industry: 'Automotive',            detail: 'Dealership branded merchandise and customer appreciation kitting.' },
  { src: logo('Volvo'),          name: 'Volvo',          industry: 'Automotive',            detail: 'Premium corporate gifting and branded collateral programs.' },
  { src: logo('DHL'),            name: 'DHL',            industry: 'Logistics',             detail: 'Workforce uniforms and branded operational materials.' },
  { src: logo('Make A Wish'),    name: 'Make A Wish',    industry: 'Non-Profit',            detail: 'Fundraising collateral, event decor, and branded merchandise.' },
  { src: logo('Timberland'),     name: 'Timberland',     industry: 'Retail & Apparel',      detail: 'Retail signage, co-packing, and product launch support.' },
  { src: logo('Samsung'),        name: 'Samsung',        industry: 'Technology',            detail: 'Consumer electronics launch activations and branded event kits.' },
];
